name: pokecard_dex
description: Una aplicación de lista infinita de Pokémon TCG.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  stream_transform: ^2.1.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

# Configuración del ícono de la app
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#DC0A2D"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
  
# Configuración del splash screen
flutter_native_splash:
  color: "#DC0A2D"
  image: assets/images/splash.png
  android: true
  ios: false
  android_12:
    color: "#DC0A2D"
    image: assets/images/splash.png
